#!/bin/bash
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config
. $control_dir/java/functions

java_opts="$(java_opts $control_dir)"

exec bash -c "
$java \
  $java_opts \
  -Dapp_port=$port \
  -Dglassfish_work_dir=\"$glassfish_work_dir\" \
  -Djava.io.tmpdir=\"$app_tmp\" \
  -Dderby.stream.error.file=\"$log_dir/derby.log\" \
  -jar $glassfish_base/modules/glassfish.jar
"
